### ISSUE TITLE
processing hanging

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#115]
**Describe the bug**
while testing silcam-gui on processing, it hangs after the following message in the log:

DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.

**To Reproduce**
processing oil data on branch 103 using windows server

**Comment by emlynjdavies** [comment]
the tensorflow debug message may be irrelevant here.

Hanging seems to occur only after measuring zero particles. is there a 'continue' somewhere after measuring zero particles that stops the neural network from loading properly?

**Comment by emlynjdavies** [comment]
from cmd execution I get the following error:

  Image 33 processed in 0.60 sec (1.7 Hz).
0.9158377647399902 Acquisition loop time
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\silcam\Scripts\silcam-script.py", line 33
, in <module>
    sys.exit(load_entry_point('PySilCam', 'console_scripts', 'silcam')())
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 97, in silcam
    silcam_process(args['<configfile>'], datapath, multiProcess=multiProcess, re
altime=False,
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 337, in silcam_proc
ess
    collector(inputQueue, outputQueue, datafilename, proc_list, False,
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 600, in collector
    write_stats(datafilename, task)
  File "c:\users\emlynd\pysilcam\pysilcam\process.py", line 534, in write_stats
    stats_all.to_hdf(fh, 'ParticleStats/stats', append=True, format='t', data_co
lumns=True)
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\core\gene
ric.py", line 2434, in to_hdf
    pytables.to_hdf(
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 270, in to_hdf
    f(store)
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 239, in <lambda>
    f = lambda store: store.append(
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 1255, in append
    self._write_to_group(
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 1788, in _write_to_group
    s.write(
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 4232, in write
    table = self._create_axes(
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 3900, in _create_axes
    data_converted = _maybe_convert_for_string_atom(
  File "C:\ProgramData\Miniconda3\envs\silcam\lib\site-packages\pandas\io\pytabl
es.py", line 4920, in _maybe_convert_for_string_atom
    if eci > itemsize:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
  Image 34 processed in 0.62 sec (1.6 Hz).
