### ISSUE TITLE
Crash processing historical data in GUI

### ISSUE THREAD

**Issue by davidrwilliamson** [SINTEF/PySilCam#147]
**Describe the bug**
Trying to use "Process historical data" on a folder of silc images in the Pysilcam GUI, I get this error:

`Process ProcThread-3:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/dave/PycharmProjects/PySilCam/pysilcam/silcamgui/guicalcs.py", line 411, in run
    import pysilcam.__main__ as psc
  File "/home/dave/PycharmProjects/PySilCam/pysilcam/__main__.py", line 19, in <module>
    import pysilcam.silcam_classify as sccl
  File "/home/dave/PycharmProjects/PySilCam/pysilcam/silcam_classify.py", line 2, in <module>
    import tflearn
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 47, in <module>
    from tensorflow.contrib import image
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 27
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):

SyntaxError: invalid syntax
`

I'm not sure whether this is an issue in my model or in the library, but I assume it is down to using a comma rather than a dot as the decimal in eye_separation and mu. Has this come up for anyone else?

**Additional context**
Error is consistent across several sets of images from different Silcams. I'm using a particle classifier model of uncertain provenance (I can't recall where I got it from), looks like it was created September 2018 so probably I have it from Bjarne or Emlyn. Have there been changes that would break old models? I can view the images fine with Silc file player.

**Comment by emlynjdavies** [comment]
doesn't look familiar to me. maybe @WillRNaylor knows?

Have you tried on the master branch?

you could also try without multiprocessing (the nomultiproc flag) to help debugging.

**Comment by davidrwilliamson** [comment]
Ah, I thought I was on master but I had the wrong branch checked out. Now I get a more helpful error message, although I'm not sure if this is also what was causing the previous error:

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/PySilCam/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/dave/PycharmProjects/PySilCam/pysilcam/silcamgui/guicalcs.py", line 414, in run
    gui=self.q, overwriteSTATS=self.overwriteSTATS)
  File "/home/dave/PycharmProjects/PySilCam/pysilcam/__main__.py", line 247, in silcam_process
    sccl.check_model(settings.NNClassify.model_path)
  File "/home/dave/PycharmProjects/PySilCam/pysilcam/silcam_classify.py", line 33, in check_model
    + 'uses a tensorflow.keras .h5 file, not a .tfl file.')
TypeError: /media/dave/DATA/model/particle-classifier.tfl is not valid hdf5 file. The predition model now uses a tensorflow.keras .h5 file, not a .tfl file.`

Do you have a pretrained model you could let me use?

**Comment by emlynjdavies** [comment]
yes, there are instructions here, with a download link:

https://github.com/SINTEF/PySilCam/wiki/Installation,-setup-and-contributions

**Comment by davidrwilliamson** [comment]
Thanks Emlyn, closing this for now.
