### ISSUE TITLE
reason for failing test with pytorch

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#19]
https://github.com/SINTEF/PySilCam/blob/a9597695d666926df2be740f2835e83eaea7b8c3/pysilcam/silcam_classify.py#L1

Traceback (most recent call last):
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/emlynd/PySilCam/pysilcam/__main__.py", line 516, in loop
    nnmodel, class_labels = sccl.load_model(model_path=settings.NNClassify.model_path)
  File "/home/emlynd/PySilCam/pysilcam/silcam_classify.py", line 157, in load_model
    map_location=lambda storage, loc: storage))  # 'cpu'
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for COAPNet:
	Unexpected key(s) in state_dict: "unit1.bn.num_batches_tracked", "unit2.bn.num_batches_tracked", "unit3.bn.num_batches_tracked", "unit4.bn.num_batches_tracked", "features.0.bn.num_batches_tracked", "features.1.bn.num_batches_tracked", "features.2.bn.num_batches_tracked", "features.3.bn.num_batches_tracked"

**Comment by aya-saad** [comment]
modified to map_location='cpu' 
please check if it still persists

**Comment by emlynjdavies** [comment]
> modified to map_location='cpu'
> please check if it still persists

unfortunately still the same.

do you have a simple example of how the load function loads the model?

**Comment by aya-saad** [comment]
the simplest is to remove map_location='cpu' parameter
but since the model was trained on a GPU I had to use this parameter to make it work locally
I removed this parameter and commit let me know if this works in your end

**Comment by emlynjdavies** [comment]
> the simplest is to remove map_location='cpu' parameter
> but since the model was trained on a GPU I had to use this parameter to make it work locally
> I removed this parameter and commit let me know if this works in your end

That causes the model to try to load from gpu, so then results in an error.

**Comment by emlynjdavies** [comment]
Does this help?

https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

**Comment by emlynjdavies** [comment]
* Initializing background image handler
* Commencing image acquisition and processing
2020-04-27 13:54:04.905413: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
2020-04-27 13:54:04.905838: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=51 error=35 : CUDA driver version is insufficient for CUDA runtime version
Process Process-1:
Traceback (most recent call last):
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/emlynd/PySilCam/pysilcam/__main__.py", line 520, in loop
    nnmodel, class_labels = sccl.load_model(model_path=settings.NNClassify.model_path)
  File "/home/emlynd/PySilCam/pysilcam/silcam_classify.py", line 161, in load_model
    model.load_state_dict(torch.load(model_path), map_location=torch.device(device))
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:51
2.0822582244873047 Acquisition loop time
1.0842833518981934 Acquisition loop time
0.8927273750305176 Acquisition loop time
0.8164727687835693 Acquisition loop time
0.7945420742034912 Acquisition loop time
0.8047306537628174 Acquisition loop time
0.8353228569030762 Acquisition loop time
0.8414187431335449 Acquisition loop time
0.771235466003418 Acquisition loop time
^Z
[3]+  Stopped                 ./emlyn_specific_test.sh

**Comment by emlynjdavies** [comment]
no longer relevant for version 0.2.10
