### ISSUE TITLE
silc file player with bmp files on linux

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#42]
**Describe the bug**
trying to view bmp files with the gui silc file player

**To Reproduce**
slected a directory of bmp silcam files and open the silc file player

**Expected behavior**
visualisation of raw images

**error**
/home/emlynd/PySilCam/pysilcam/silcamgui/guicalcs.py:258: RuntimeWarning: use font: libSDL_ttf-2.0.so.0: cannot open shared object file: No such file or directory
(ImportError: libSDL_ttf-2.0.so.0: cannot open shared object file: No such file or directory)
  font = pygame.font.SysFont("monospace", 20)
Traceback (most recent call last):
  File "/home/emlynd/PySilCam/pysilcam/silcamgui/silcamgui.py", line 722, in silc_player
    gc.silcview(self.datadir)
  File "/home/emlynd/PySilCam/pysilcam/silcamgui/guicalcs.py", line 258, in silcview
    font = pygame.font.SysFont("monospace", 20)
  File "/home/emlynd/anaconda3/envs/silcam/lib/python3.5/site-packages/pygame/__init__.py", line 105, in __getattr__
    raise NotImplementedError(MissingPygameModule)
NotImplementedError: font module not available
(ImportError: libSDL_ttf-2.0.so.0: cannot open shared object file: No such file or directory)
Aborted (core dumped)

**Comment by emlynjdavies** [comment]
@davidrwilliamson did you experience this when you worked on this recently? looks like a dependency issue.

**Comment by davidrwilliamson** [comment]
I don't recall exactly but I did have the odd dependency issue. I will check my notes and see if I had to fix this one.

**Comment by emlynjdavies** [comment]
@davidrwilliamson did you find out if you already fixed this?

**Comment by davidrwilliamson** [comment]
I built a new conda environment from environment.yml and tested this on my home machine, I can't reproduce the problem there.

**Comment by emlynjdavies** [comment]
ah. OK. I guess the monospace error is another issue. might be that the bmp reading here has been fixed by another recent update.

If you get the monospace error again, perhaps you can log a new issue for follow-up or documenting as an install requirement, @davidrwilliamson? :)
