### ISSUE TITLE
Get an exe install to work

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#72]
https://github.com/SINTEF/PySilCam/blob/pyinstaller/windows_installer

or py2exe

spend some minutes trying out of the box solutions.

**Comment by emlynjdavies** [comment]
Traceback (most recent call last):
File "pysilcam\silcamgui\silcamgui.py", line 22, in <module>
File "<frozen importlib._bootstrap>", line 968, in _find_and_load
File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "c:\users\emlynd\anaconda3\envs\silcam\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.__dict__)
File "pysilcam\oilgas.py", line 21, in <module>
File "<frozen importlib._bootstrap>", line 968, in _find_and_load
File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "c:\users\emlynd\anaconda3\envs\silcam\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.__dict__)
File "cmocean\__init__.py", line 11, in <module>
File "<frozen importlib._bootstrap>", line 968, in _find_and_load
File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "c:\users\emlynd\anaconda3\envs\silcam\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.__dict__)
File "cmocean\cm.py", line 32, in <module>
File "numpy\lib\npyio.py", line 926, in loadtxt
File "numpy\lib\_datasource.py", line 262, in open
File "numpy\lib\_datasource.py", line 618, in open
OSError: C:\Users\emlynd\AppData\Local\Temp\_MEI140722\cmocean\rgb\thermal-rgb.txt not found.
[8648] Failed to execute script silcamgui

**Comment by nepstad** [comment]
Try:
import os
import cmocean
cmocean_data_path = os.path.join(cmocean.__path__, 'rbg')
datas=[os.path.join(cmocean_data_path, f) for f in os.listdir(cmocean_data_path)]

**Comment by emlynjdavies** [comment]
regarding hardware dependency installs, see this for including apt-get type commands within setuptools:
https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools
